python:
  - 3.13
  - 3.12
  - 3.11
  - 3.10
package_name:
  - crossroad

# Add channel configuration
channels:
  - conda-forge
  - bioconda
  - pranjalpruthi
  - defaults

# Add build configuration
build:
  noarch: python
  preserve_egg_dir: False
